eval "$(rbenv init -)"
export PATH=/usr/local/bin:$PATH
export ANDROID_HOME=/Applications/android-sdk-macosx
export PATH=$ANDROID_HOME:$ANDROID_HOME/tools/:$PATH

[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh  # This loads NVM4

alias ls='ls -G'
export CLICOLOR=1
export LSCOLORS=Gxfxcxdxbxegedabagacad
export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  source $(brew --prefix)/etc/bash_completion
fi

# Flexport tests
export FLEXPORT_SUPPORT_EMAIL='tuan@flexport.com'
rtest ()
{
  RAILS_ENV=test rake db:migrate
  if [ $# -ne 0 ]; then
    bundle exec rpsec
  else
    bundle exec rspec $1
  fi;
}


source ~/.git_aliases  # git aliases

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

##
# Your previous /Users/tbui/.bash_profile file was backed up as /Users/tbui/.bash_profile.macports-saved_2015-01-17_at_12:23:44
##

# MacPorts Installer addition on 2015-01-17_at_12:23:44: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

